### ISSUE TITLE
Fails to build on OSX 10.9.2 - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ckm2k1** [andrewrk/libgroove#55]
cmake runs fine, but make fails with the following output:

```
Undefined symbols for architecture x86_64:
  "_ebur128_true_peak", referenced from:
      _emit_track_info in loudness.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgrooveloudness.3.1.1.dylib] Error 1
make[1]: *** [CMakeFiles/grooveloudness.dir/all] Error 2
make: *** [all] Error 2
```

I do have the latest XCode with command line tools installed. Googling around
point to this possibly being an issue related to the stdlib used, but I'm not sure how to 
resolve the issue in the cmake files. 

Summary from cmake, just in case: 

```
Installation Summary
--------------------
* Install Directory            : /usr/local
* Build libgroove              : yes
* Build libgrooveplayer        : yes
* Build libgrooveloudness      : yes
* Build libgroovefingerprinter : yes

Bundled Dependencies
--------------------
* SDL2                         : ready to build
* libav                        : using system libraries
* libebur128                   : ready to build

System Dependencies
-------------------
* C99 Compiler                 : OK
* threads                      : OK
* SDL2                         : not found - will use bundled version
* ebur128                      : not found - will use bundled version
* chromaprint                  : OK
* libavformat                  : OK
* libavcodec                   : OK
* libavfilter                  : OK
* libavutil                    : OK
```

Some version info: 

```
$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix
```

XCode version: 5.1.1
