### ISSUE TITLE
undefined reference to `ebur128_true_peak' while building on Gentoo

### ISSUE THREAD

**Issue by espenaf** [andrewrk/libgroove#56]
Hi
I have created a installation script (ebuild) for installation of libgroove on Gentoo. The ebuild works fine with libgroove 3.0.6, but only after I forced the building of the internal libav, as my Gentoo box uses ffmpeg. Gentoo makes it possible to use either, It`s your choice. To force libav I had to add the following while configuring CMake:

``` bash
"-DLIBAV_AVCODEC_LIBRARY="
"-DLIBAV_AVFILTER_LIBRARY="
"-DLIBAV_AVFORMAT_LIBRARY="
"-DLIBAV_AVUTIL_LIBRARY="
```

This worked as I said up until version 3.0.7 where I a suddenly getting some problems with a undefined reference to ebur128_true_peak. I suspect this is relates to e4a0d680c4f91639a1ba5d5204378753083d1dd6, where you use start using ebur128_true_peak. The libebur128 library isn`t available in Gentoo yet, so I want it to use the bundled version. In the configuration part below it seems that this is the case, but I still get an undefined reference. Any suggestions?

``` bash
cmake --no-warn-unused-cli -C /var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DLIBAV_AVCODEC_LIBRARY= -DLIBAV_AVFILTER_LIBRARY= -DLIBAV_AVFORMAT_LIBRARY= -DLIBAV_AVUTIL_LIBRARY= -DEBUR128_IS_BUNDLED= -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/gentoo_rules.cmake  /var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
Configuring libgroove version 3.1.1
Configuring libgrooveplayer version 3.1.1
Configuring libgrooveloudness version 3.1.1
Configuring libgroovefingerprinter version 3.1.1
-- Try C99 C flag = [ ]
-- Performing Test C99_FLAG_DETECTED
-- Performing Test C99_FLAG_DETECTED - Failed
-- Try C99 C flag = [-std=c99]
-- Performing Test C99_FLAG_DETECTED
-- Performing Test C99_FLAG_DETECTED - Success
-- Found PkgConfig: /usr/bin/x86_64-pc-linux-gnu-pkg-config (found version "0.28") 
-- checking for module 'speexdsp'
--   package 'speexdsp' not found
-- checking for module 'libchromaprint'
--   found libchromaprint, version 1.1.0
-- Found Chromaprint: /usr/lib64/libchromaprint.so  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib64/libSDL2main.so;/usr/lib64/libSDL2.so;-lpthread  
-- Found LibAV: /usr (Required is at least version "10.0") found components:  avdevice swscale missing components:  avcodec avfilter avformat avutil
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Found components for Yasm
-- YASM_INCLUDES  = /usr/include
-- YASM_LIBRARIES = /usr/lib64/libyasm.a
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
CMake Warning (dev) at CMakeLists.txt:277 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The plain signature for target_link_libraries has already been used with
  the target "groove".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * CMakeLists.txt:254 (target_link_libraries)
   * CMakeLists.txt:265 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:369 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "grooveloudness".  All uses of target_link_libraries with a
  target should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:366 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.


Installation Summary
--------------------
* Install Directory            : /usr
* Build libgroove              : yes
* Build libgrooveplayer        : yes
* Build libgrooveloudness      : yes
* Build libgroovefingerprinter : yes

Bundled Dependencies
--------------------
* SDL2                         : using system library
* libav                        : ready to build
* libebur128                   : ready to build

System Dependencies
-------------------
* C99 Compiler                 : OK
* threads                      : OK
* SDL2                         : OK
* ebur128                      : not found - will use bundled version
* chromaprint                  : OK
* libavformat                  : not found - will use bundled version
* libavcodec                   : not found - will use bundled version
* libavfilter                  : not found - will use bundled version
* libavutil                    : not found - will use bundled version
* yasm                         : OK
* bzip2                        : OK
* mp3lame                      : OK
* zlib                         : OK

If everything is looks good, proceed with
make

-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -march=native -O2 -pipe 
C++             
Linker flags:
Executable       -Wl,-O1 -Wl,--as-needed
Module           -Wl,-O1 -Wl,--as-needed
Shared           -Wl,-O1 -Wl,--as-needed

-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "groove" has an INTERFACE_LINK_LIBRARIES property which differs from
  its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

    dl;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libavfilter.a;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libavformat.a;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libavcodec.a;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libavresample.a;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libswscale.a;/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/lib/libavutil.a;/usr/lib64/libbz2.so;/usr/lib64/libz.so;/usr/lib64/libmp3lame.so;-lpthread

  LINK_INTERFACE_LIBRARIES:

    -lpthread

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "grooveloudness" has an INTERFACE_LINK_LIBRARIES property which
  differs from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

    groove;-lpthread;ebur128_static

  LINK_INTERFACE_LIBRARIES:

    groove;-lpthread

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
```

``` bash
Building C object CMakeFiles/playlist.dir/example/playlist.c.o
/usr/bin/x86_64-pc-linux-gnu-gcc    -DNDEBUG -march=native -O2 -pipe  -I/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build -I/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/deps/libav/install/include -I/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1 -I/usr/include/SDL2 -I/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1/deps/ebur128    -std=c99 -pedantic -Werror -Wall -g -o CMakeFiles/playlist.dir/example/playlist.c.o -c /var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1/example/playlist.c
make[2]: Leaving directory `/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build'
/usr/bin/cmake -E cmake_progress_report /var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build/CMakeFiles  33
[100%] Built target transcode
libgrooveloudness.so.3.1.1: undefined reference to `ebur128_true_peak'
collect2: error: ld returned 1 exit status
make[2]: *** [replaygain] Error 1
make[2]: Leaving directory `/var/tmp/portage/media-libs/libgroove-3.1.1/work/libgroove-3.1.1_build'
make[1]: *** [CMakeFiles/replaygain.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
